name: label-coach
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - gdk-pixbuf=2.32.2=1
  - openslide=3.4.1=2
  - ca-certificates=2018.4.16=0
  - cairo=1.14.12=he56eebe_3
  - certifi=2018.4.16=py36_0
  - fontconfig=2.13.0=h074f895_3
  - freetype=2.8.1=0
  - gettext=0.19.8.1=0
  - glib=2.55.0=0
  - gobject-introspection=1.55.0=py36h3a3fb3b_0
  - icu=58.2=hfc679d8_0
  - jpeg=9c=h470a237_0
  - libffi=3.2.1=3
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=7.2.0=hdf63c60_3
  - libiconv=1.15=h470a237_1
  - libpng=1.6.34=ha92aebf_1
  - libstdcxx-ng=7.2.0=hdf63c60_3
  - libtiff=4.0.9=he6b73bb_1
  - libxcb=1.13=h470a237_2
  - libxml2=2.9.8=h422b904_2
  - ncurses=5.9=10
  - openjpeg=2.3.0=h0e734dc_3
  - openssl=1.0.2o=0
  - pcre=8.41=1
  - pip=9.0.3=py36_0
  - pixman=0.34.0=2
  - pthread-stubs=0.4=h470a237_1
  - python=3.6.5=1
  - readline=7.0=0
  - setuptools=40.0.0=py36_0
  - sqlite=3.20.1=2
  - tk=8.6.8=0
  - wheel=0.31.1=py36_0
  - xorg-kbproto=1.0.7=h470a237_2
  - xorg-libice=1.0.9=h470a237_4
  - xorg-libsm=1.2.2=h470a237_4
  - xorg-libx11=1.6.5=h470a237_2
  - xorg-libxau=1.0.8=h470a237_6
  - xorg-libxdmcp=1.1.2=h470a237_7
  - xorg-libxext=1.3.3=h470a237_4
  - xorg-libxrender=0.9.10=h470a237_2
  - xorg-renderproto=0.11.1=h470a237_2
  - xorg-xextproto=7.3.0=h470a237_2
  - xorg-xproto=7.0.31=h470a237_7
  - xz=5.2.3=0
  - zlib=1.2.11=h470a237_3
  - pip:
    - apipkg==1.5
    - asn1crypto==0.24.0
    - atomicwrites==1.1.5
    - attrs==18.1.0
    - aws-xray-sdk==0.95
    - backports.functools-lru-cache==1.5
    - bcrypt==3.1.4
    - boto==2.49.0
    - boto3==1.7.62
    - botocore==1.10.62
    - cffi==1.11.5
    - chardet==3.0.4
    - cheroot==6.3.3
    - cherrypy==11.0.0
    - click==6.7
    - click-plugins==1.0.3
    - cookies==2.2.1
    - coverage==4.5.1
    - cryptography==2.3
    - docker==3.4.1
    - docker-pycreds==0.3.0
    - docutils==0.14
    - dogpile.cache==0.6.6
    - execnet==1.5.0
    - filelock==3.0.4
    - flake8==3.5.0
    - flake8-blind-except==0.1.1
    - flake8-docstrings==1.3.0
    - flake8-polyfill==1.0.2
    - flask==1.0.2
    - girder==2.5.0
    - httmock==1.2.6
    - idna==2.7
    - itsdangerous==0.24
    - jaraco.functools==1.20
    - jinja2==2.10
    - jmespath==0.9.3
    - jsondiff==1.1.1
    - jsonpickle==0.9.6
    - jsonschema==2.6.0
    - mako==1.0.7
    - markupsafe==1.0
    - mccabe==0.6.1
    - mock==2.0.0
    - mongomock==3.10.0
    - more-itertools==4.2.0
    - moto==1.3.3
    - openslide-python==1.1.1
    - packaging==17.1
    - pbr==4.1.1
    - pillow==5.2.0
    - pluggy==0.6.0
    - portend==2.3
    - psutil==5.4.6
    - py==1.5.4
    - pyaml==17.12.1
    - pycodestyle==2.3.1
    - pycparser==2.18
    - pydocstyle==2.1.1
    - pyflakes==1.6.0
    - pymongo==3.7.1
    - pyparsing==2.2.0
    - pytest==3.6.3
    - pytest-cov==2.5.1
    - pytest-forked==0.2
    - pytest-girder==0.0.1
    - pytest-xdist==1.22.2
    - python-dateutil==2.6.1
    - pytz==2018.5
    - pyyaml==3.13
    - requests==2.19.1
    - responses==0.9.0
    - s3transfer==0.1.13
    - sentinels==1.0.0
    - six==1.11.0
    - snowballstemmer==1.2.1
    - tempora==1.13
    - tox==3.1.2
    - urllib3==1.23
    - virtualenv==16.0.0
    - websocket-client==0.48.0
    - werkzeug==0.14.1
    - wrapt==1.10.11
    - xmltodict==0.11.0
prefix: /home/chaitanya/anaconda3/envs/label-coach

